name: rt
channels:
  - salilab
  - cogsci
  - conda-forge
  - defaults
dependencies:
  - pygame=1.9.2a0=py35_0
  - bkcharts=0.2=py35_0
  - bleach=2.1.3=py_0
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2016.2.28=py35_0
  - colorama=0.3.9=py_1
  - cycler=0.10.0=py35_0
  - decorator=4.2.1=py35_0
  - entrypoints=0.2.3=py35_1
  - expat=2.1.0=0
  - fontconfig=2.13.1=he21cea1_0
  - freetype=2.9.1=he8b6a0d_4
  - gettext=0.19.8.1=hb01d8f6_1001
  - glib=2.56.2=h5b73faf_0
  - html5lib=1.0.1=py_0
  - icu=58.2=vc14_0
  - ipykernel=4.8.2=py35_0
  - ipympl=0.1.0=py35_1
  - ipython=6.2.1=py35_1
  - ipython_genutils=0.2.0=py35_0
  - ipywidgets=7.1.2=py35_0
  - jedi=0.11.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=vc14_2
  - jsonschema=2.6.0=py35_1
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.31.12=py35_1
  - jupyterlab_launcher=0.10.5=py35_0
  - libffi=3.2.1=h6538335_1005
  - libiconv=1.15=hfa6e2cd_1003
  - libpng=1.6.34=vc14_0
  - libsodium=1.0.16=vc14_0
  - libxml2=2.9.8=h9ce36c8_4
  - markupsafe=1.0=py35_0
  - mistune=0.8.3=py_0
  - mpld3=0.2=py35_0
  - mplexporter=0.0.1=py_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py35_0
  - netifaces=0.10.7=py35_0
  - notebook=5.4.1=py35_0
  - openssl=1.0.2p=hfa6e2cd_1000
  - pandoc=2.1.3=0
  - pandocfilters=1.4.1=py35_0
  - parso=0.1.1=py_0
  - patsy=0.4.1=py35_0
  - pcre=8.41=vc14_1
  - pexpect=4.4.0=py35_0
  - pickleshare=0.7.4=py35_0
  - prompt_toolkit=1.0.15=py35_0
  - pygments=2.2.0=py35_0
  - pyparsing=2.2.0=py35_0
  - pyqt=5.6.0=py35_2
  - python=3.5.4=0
  - python-dateutil=2.7.2=py_0
  - pytz=2017.2=py35_0
  - pywinpty=0.5.4=py35_2
  - pyyaml=3.12=py35_0
  - pyzmq=17.0.0=py35_3
  - qt=5.6.2=vc14_1
  - seaborn=0.8.0=py35_0
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py35_0
  - sip=4.18=py35_0
  - six=1.11.0=py35_1
  - sqlite=3.22.0=vc14_0
  - terminado=0.8.1=py35_0
  - testpath=0.3.1=py35_0
  - tk=8.5.19=vc14_1
  - tornado=5.0.1=py35_1
  - traitlets=4.3.2=py35_0
  - vc=14=0
  - vs2015_runtime=14.0.25420=0
  - wcwidth=0.1.7=py35_0
  - webencodings=0.5=py35_0
  - wheel=0.29.0=py35_0
  - widgetsnbextension=3.1.4=py35_0
  - win_unicode_console=0.5=py35_0
  - wincertstore=0.2=py35_2
  - winpty=0.4.3=4
  - xz=5.2.3=0
  - zeromq=4.2.5=vc14_2
  - zlib=1.2.11=vc14_0
  - blas=1.0=mkl
  - bokeh=0.12.7=py35_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=2.0.2=np113py35_0
  - mkl=2017.0.3=0
  - msys2-conda-epoch=20160418=1
  - numpy=1.13.1=py35_0
  - pandas=0.20.3=py35_0
  - pip=10.0.1=py35_0
  - requests=2.14.2=py35_0
  - scipy=0.19.1=np113py35_0
  - setuptools=36.4.0=py35_1
  - statsmodels=0.8.0=np113py35_0
  - yaml=0.1.6=0
  - gmp=5.0.1=0
prefix: C:\Users\thomasD\AppData\Local\Continuum\anaconda3\envs\rt
